#!/bin/bash
mkdir ~/biostudies_ftp
# echo 'nohup rclone mount biostudies:biostudies/nfs ~/biostudies --daemon > rclone.log &' >> ~/.bashrc 
nohup rclone mount biostudies:biostudies/nfs ~/biostudies_ftp --read-only --daemon </dev/null >/dev/null 2>&1 &

mkdir ~/fg_bioimage
nohup rclone mount fg_bioimage: ~/fg_bioimage --read-only --daemon </dev/null >/dev/null 2>&1 &

exec "$@"

# https://discourse.jupyter.org/t/storage-capacity-is-not-respected-by-hub/8080/2
# screen -d -m bash -c "rclone mount biostudies:biostudies/nfs ~/biostudies --daemon -vv"
# nohup rclone mount biostudies:biostudies/nfs ~/biostudies --daemon ;
