#!/bin/bash
mkdir ~/biostudies
exec "$@"

# https://discourse.jupyter.org/t/storage-capacity-is-not-respected-by-hub/8080/2
# screen -d -m bash -c "rclone mount biostudies:biostudies/nfs ~/biostudies --daemon -vv"
# nohup rclone mount biostudies:biostudies/nfs ~/biostudies --daemon ;
